version: "v1.0"

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: career-jump:latest
    container_name: career-jump
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus
    volumes:
      # 현재 디렉토리의 prometheus.yml 파일을 컨테이너의 /etc/prometheus/prometheus.yml 위치에 마운트
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"