spring:
  config:
    name:
      monitor

server:
  tomcat:
    mbeanregistry:
      enabled: true # actuator 에서 tomcat metric 을 모두 사용하게 하기 위함

# actuator 설정
management:
  server:
    port: 8081
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    git:
      mode: full # actuator/info 에서 git 정보를 디테일하게 보고싶을 때
  endpoint:
    health:
      show-details: always    # health 정보를 자세히 보고싶을 때 사용
#      show-components: always # health 정보를 자세히 띄우는 것이 부담스러울 때 (Default Option)
  endpoints:
    web:
      exposure:
        include: "*"          # actuator 포함할 metrics
        exclude: "env, beans" # actuator 제외할 metrics
      base-path: "/manage"


info:  # actuator env -> true 일 때, 이런 env 정보 표시
  app:
    name: hello-actuator
    company: dj
