spring:
  profiles:
    active: local
    group:
      local: local, swagger, oauth, s3, monitor
      dev: dev, swagger, oauth, s3, monitor
  application:
    name:
      careerjump

logging:
  level:
    org.hibernate.sql: debug
    org.careerjump.server.log: trace