#spring:
#  config:
#    activate:
#      on-profile: local, dev
#  application:
#    name:
#      careerjump
spring:
  config:
    name:
      oauth
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 611787981d99bd90f99830f819b83b52
            client-secret: wZkjsILGamV9bQwvUcMsOT2iuMqcex6s
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: # kakao 개인 정보 동의 항목 설정의 ID 값
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id