spring:
  profiles:
    active: prod
    group:
      local: local, swagger, oauth, s3, monitor
      dev: dev, swagger, oauth, s3, monitor
      prod: prod, swagger, oauth, s3, monitor
  application:
    name:
      careerjump

logging:
  level:
    org.hibernate.sql: debug
    org.careerjump.server: debug
#    org.careerjump.server.log: trace

server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: jigooin1234!
    key-store-type: PKCS12
  port: 8080